name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./my-react-app

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test (jest)
        run: npm run test

      - name: Test (playwright)
        run: |
          npx playwright install chromium
          npm run test-pw
